apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kevin
spec:
  interval: 10m0s
  timeout: 2m0s
  targetNamespace: tenant-compsoc
  sourceRef:
    kind: GitRepository
    name: tenant-repository
  path: ./apps/kevin
  prune: true
  force: true
  wait: true